yarnPath: .yarn/releases/yarn-3.3.0.cjs
# by default offline cache (in .yarn/cache) is leveraged to power PnP (files are read directly from within the zip archives)
# use your computer's global cache in /username/.yarn/.cache
# enableGlobalCache: true
# use for compatibility with programs that need node_modules folder
# nodeLinker: node-modules
